/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package LoteriaDiogistica;

import javax.swing.JOptionPane;

public class App {
    

    public static void main(String[] args) {
        Sorteio sorteioDeHoje = new Sorteio();
        String resultado = sorteioDeHoje.sorteiaNumero();
        JOptionPane.showMessageDialog(null,resultado);

    }
}
